# Generated by Django 2.2.1 on 2019-09-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lat', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
                ('_long', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
                ('_lat1', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
                ('_long2', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
            ],
        ),
    ]
