# Generated by Django 2.2.1 on 2019-09-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygen', '0002_twopoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twopoints',
            old_name='_long2',
            new_name='_long1',
        ),
    ]
